# -*- coding: utf-8 -*-
"""Mathematical Modeller for exponential growth models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dp1fqM1PnWl0eCfMLIqyVteIJBg5dTJb
"""

import math
import matplotlib.pyplot as plt
print("Mathematical Modeller for exponential growth models")
print()
dep = input("Enter the name of the dependant variable: ")
indep = input("Enter the name of the independant variable: ")
e = math.e
print("Enter any value of the", dep, "from the available data set: ")
x1 = float(input())
print("Enter the correspondng",indep,"value for the entered ",dep," value: ")
y1 = float(input())
print("Enter another value of the", dep, "from the available data set: ")
x2 = float(input())
print("Enter the correspondng",indep,"value for the previously entered ",dep," value: ")
y2 = float(input())
print()
def gettingcustomval():
  print()
  print("Getting Custom Values: ")
  print()
  print("Enter which value you would like to pass: ",dep,"(1) or",indep,"(2)")
  what = int(input())
  if what == 1:
      print ("Enter the value of",dep)
      hi = float(input())
      h = hi/c
      g = math.log(h)
      bye = g/k
      print ("The corresponding ",indep,"value for",hi,"of",dep,"is: ",round(bye))
  elif what == 2:
      print("Enter the value of",indep)
      hi = float(input())
      bye = c*(e**(k*hi))
      print("The corresponding",dep,"value for",hi,"of",indep,"is ",(bye))
def plotting():
  print()
  print("Plotting the graph")
  print()
  xval = []
  yval = []
  print("Enter the minimum value of ",indep)
  sta = float(input())
  print("Enter the maximum value of ",indep)
  end = float(input())
  for i in range (int(sta),int(end),1):
    xval.append(i)
  for j in xval:
    bye = c*(e**(k*j))
    yval.append(bye)
  labe = indep,"vs",dep
  plt.plot(xval,yval,label = labe)
  plt.xlabel(indep)
  plt.ylabel(dep)
  plt.legend()
  plt.show()
if x1==0:
    print("ALERT: Please enter a non-zero value for the first value of",dep)
elif x2==0:
    print("ALERT: Please enter a non-zero value for the second value of",dep)
else:
    a = 1/(x1/x2)
    l =  math.log(a)
    k = l/(y1-y2)
    if k<0:
        k = (-1)*k
    upper = k*y1
    withe = e**upper
    c = x1/withe
    print("The required mathematical model is:", dep ,"=",c,"*e^(",k,"*",indep,")")
    print()
    print("Press 1 if you want to enter a value for",dep,"or",indep, "to get the corresponding value. Press 2 if you want to get the graph of the model. Press 3 to do both. Press any key to end the process.")
    cont = (input())
    if cont == "1":
      gettingcustomval()
    elif cont == "2":
      plotting()
    elif cont == "3":
      gettingcustomval()
      plotting()
    else:
        print("Thank you!")